### ISSUE TITLE
Duplicate messages

### ISSUE THREAD

**Issue by plaksina** [confluentinc/kafka-connect-jdbc#173]
While running kafka jdbc connector in standalone connector in incrementing mode,
Connector keeps creating multiple messages for one row inserted.
We have a column specified with sequence auto increment

Any suggestons ?

**Comment by shikhar** [comment]
I can only imagine this happening if the connector is failing to commit offsets. Can you provide logs from the Connect worker?

**Comment by rnpridgeon** [comment]
You may want to consider setting the connector to use Upserts as opposed to Inserts as described here. 

http://docs.confluent.io/3.1.2/connect/connect-jdbc/docs/sink_connector.html#idempotent-writes

I'll go ahead and close this for now since it's been over a month. Feel free to reopen when you have the logs requested by @shikhar
