### ISSUE TITLE
Confluent Kafka JDBC Connect does not work with tables without a timestamp or incrementing id field

### ISSUE THREAD

**Issue by avinashramesh** [confluentinc/kafka-connect-jdbc#204]
Hi Team,

We are trying to configure Kafka JDBC connect in order to have streams from an audit table. The audit table unfortunately doesn't have a rich set of timestamp or id fields that auto increment. As of now we have created triggers on these audit tables to move the records to another custom table we created with a custom id and timestamp field. But this idea is not going to fly in production as the customers may not be happy doing custom tables and custom triggers. We did try the bulk option, but then the processing goes in an endless loop while trying to read it from avro consumer (but the bulk table option is not going to take-off either as the audit tables are going to be huge).

Please could we have something more intuitive on JDBC connect to use any non-numeric fields also to determine or identify new rows added to the table.

Regards
Avinash

**Comment by wushujames** [comment]
kafka-connect-jdbc lets you specify a custom SQL query. Would that work for your needs? http://docs.confluent.io/3.2.0/connect/connect-jdbc/docs/source_connector.html#incremental-query-modes

**Comment by avinashramesh** [comment]
Hi Wushu,

We would like to detect new rows getting added or existing rows getting updated. The custom query could help us filter some data but not sure if we could detect something new or changes to a tuple.

Regards
AVinash

Sent from my iPhone

On 27 Mar 2017, at 18:57, wushujames <notifications@github.com<mailto:notifications@github.com>> wrote:


kafka-connect-jdbc lets you specify a custom SQL query. Would that work for your needs? http://docs.confluent.io/3.2.0/connect/connect-jdbc/docs/source_connector.html#incremental-query-modes<https://urldefense.proofpoint.com/v2/url?u=http-3A__docs.confluent.io_3.2.0_connect_connect-2Djdbc_docs_source-5Fconnector.html-23incremental-2Dquery-2Dmodes&d=DwMFaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=iQ1hRzh-ra8q3FXq31z7660gSWXRwhcdL5f0llThLbg&m=BAiwjU14s9mw2NZga4M9cnrITbQThw7K2TuJfg8_f_Q&s=18llumpzTq3Oj9Q2-0jvwk44MVKuoi-ythbksnOHA2E&e=>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_confluentinc_kafka-2Dconnect-2Djdbc_issues_204-23issuecomment-2D289533076&d=DwMFaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=iQ1hRzh-ra8q3FXq31z7660gSWXRwhcdL5f0llThLbg&m=BAiwjU14s9mw2NZga4M9cnrITbQThw7K2TuJfg8_f_Q&s=62shULjwbriDQRt2zTzAaBh_m-3-2MgqazmjhM8vuqg&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AZe587M-5F9okrBulYzYsheFH6UsVqXiudks5rp-5FiNgaJpZM4Mqj5C&d=DwMFaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=iQ1hRzh-ra8q3FXq31z7660gSWXRwhcdL5f0llThLbg&m=BAiwjU14s9mw2NZga4M9cnrITbQThw7K2TuJfg8_f_Q&s=Zb6I8hjAk9QKWXXgu3Xi4wLx-Fi_T0fQKWLFETk8k9Q&e=>.

________________________________

This message is for the designated recipient only and may contain privileged, proprietary, or otherwise confidential information. If you have received it in error, please notify the sender immediately and delete the original. Any other use of the e-mail by you is prohibited. Where allowed by local law, electronic communications with Accenture and its affiliates, including e-mail and instant messaging (including content), may be scanned by our systems for the purposes of information security and assessment of internal compliance with Accenture policy.
______________________________________________________________________________________

www.accenture.com

**Comment by gwenshap** [comment]
Any suggestion on how would you use anything besides dates and numbers to incrementally get new rows? It just doesn't sound feasible to me, but I may be missing something.

I'd say that if your audit table doesn't have time stamps, you may have a bigger problem at hand.... how do you know when the event you are auditing happened?

**Comment by avinashramesh** [comment]
I think there are quite some products that do not use incrementing numbers as primary key to uniquely identify a row, rather generate something like a long alphanumeric string for each row added to a table. So can we extend it beyond only numbers? The audit table we are talking about uses a long unique alphanumeric string as the primary key (like the GUID generated for each java class)

In regard to detecting updates, yeah from a table level it is a bit difficult apart from time stamp to credibly identify rows updates without fully comparing all the old and new values. Might need a more deep inspection logic ( like how a DB trigger works)

Regards
AR

Sent from my iPhone

On 14 Apr 2017, at 16:30, Gwen (Chen) Shapira <notifications@github.com<mailto:notifications@github.com>> wrote:


Any suggestion on how would you use anything besides dates and numbers to incrementally get new rows? It just doesn't sound feasible to me, but I may be missing something.

I'd say that if your audit table doesn't have time stamps, you may have a bigger problem at hand.... how do you know when the event you are auditing happened?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_confluentinc_kafka-2Dconnect-2Djdbc_issues_204-23issuecomment-2D294174483&d=DwMFaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=iQ1hRzh-ra8q3FXq31z7660gSWXRwhcdL5f0llThLbg&m=fsOHYRU1kfvupUjRcU9R88Xfu-zj2Rk9fuQx_cMG9vA&s=KeBBU7hULUKnX8EUpt19l42XNd_ZgDFAvSaAm_w0GZA&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AZe588lOHhuAV87Zn-5FwxIrtd3zGOKX-2D7ks5rv5D5gaJpZM4Mqj5C&d=DwMFaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=iQ1hRzh-ra8q3FXq31z7660gSWXRwhcdL5f0llThLbg&m=fsOHYRU1kfvupUjRcU9R88Xfu-zj2Rk9fuQx_cMG9vA&s=q6V5gq_CdYgSno6g-XT2u1V_WLi4qOGF0hq7O7Carog&e=>.

________________________________

This message is for the designated recipient only and may contain privileged, proprietary, or otherwise confidential information. If you have received it in error, please notify the sender immediately and delete the original. Any other use of the e-mail by you is prohibited. Where allowed by local law, electronic communications with Accenture and its affiliates, including e-mail and instant messaging (including content), may be scanned by our systems for the purposes of information security and assessment of internal compliance with Accenture policy.
______________________________________________________________________________________

www.accenture.com

**Comment by vara-bonthu** [comment]
To get around this issue i have created a VIEW with additional columns as rownum and SYSTIMESTAMP. see if this helps as workaround

CREATE OR REPLACE VIEW vw_users AS
SELECT rownum as ids, SYSTIMESTAMP as modified,  t.*
FROM (SELECT * FROM users_test) t

**Comment by wicknicks** [comment]
@vara-bonthu: the jdbc connector allows you to specify a custom query as shown here (https://docs.confluent.io/current/connect/connect-jdbc/docs/source_connector.html), which can be used to pull new updates. Would that work for you?

**Comment by nik09541** [comment]
Hi @wicknicks

I have tried to configure Kafka JDBC connect in order to have streams from an existing table. The existing table unfortunately have a id field that has purging from another event(i.e the rows are not strictly incrementing). As of now we have created script to move the records to another custom table we created with a custom id and timestamp field. But this is not working.During the first insert into custom table with data from existing table there is no event seen on kafka topic. But on updating the timestamp column the event is noticed on connectror. I did try the bulk option, but then the processing goes in an endless loop while trying to read it from avro consumer (but the bulk table option is not going to take-off either as the audit tables are going to be huge).

insert into reference (select * from customer where customer_ref_id in (5004145,5004146,5004161,5004162,5004178));
Above insert registers no event in kafka connector as id id not strictly incrementing in customer table.

insert into reference (customer_ref_id ,updated_date) values (id_seq.nextval,current_timestamp);
This insert works as it is inserting data with a sequence into table. Event is noticed on kafka connector

I have tried the query mode also it also doesnt work.

Please help if we can poll out the existing data on kafka topic for a non incrementing exisiting id of a table which is having purging .

**Comment by rhauch** [comment]
This connector likely will not work for continually getting new records from tables that don't have a way of querying for what has changed. You might consider a CDC-type solution, which often don't use queries and can discover individual row inserts, updates, and deletes.

**Comment by nik09541** [comment]
Hi @rhauch 
Is there any way to control the bulk mode so that it does not go in endless loop in case we are looking to poll data from existing table.
Secondly is there any way connector can poll data from existing table where Id column is not strictly incrementing. The reason for non incrementing Id's is that we have purging introduced due to which some records get inserted in to  the table and others not based on a condition. Intend here is to work with timestamp+incrementing mode so that we can detect the polling into new custom table from existing table and check inserts + updates.  Here in this case only update registers an event for first time entry into custom table from existing one  but not for insert.
