### ISSUE TITLE
KAFKA Connect - Distributed

### ISSUE THREAD

**Issue by SaravananVT** [confluentinc/kafka-connect-jdbc#30]
Has anybody tried executing this JDBC connect in distributed mode with multiple workers. I am looking for a process to split the task assignment across different workers\connectors.

regards
Saravanan

**Comment by ewencp** [comment]
@SaravananVT Yes! We have system tests to validate this functionality works as expected, even in the face of failures. If you submit a JDBC connector to a distributed cluster, it will divide the work up by the available tables. So, for example, if you had tables `users`, `products`, and `orders`, it would divide the work into at most 3 tasks which would automatically be scheduled to run across available workers.

In terms of configuration, you shouldn't need to change anything compared to standalone mode. The only setting you might want to adjust is `tasks.max` since you might have a default setting of only `1`.

(The code may not directly be useful to you, but a test case example is [here](https://github.com/confluentinc/muckrake/blob/master/muckrake/tests/connect_mysql_distributed_test.py#L25)).

**Comment by SaravananVT** [comment]
Thanks a lot .. I have few more clarifications on the design and how the framework actually does the distribution and coordination between the workers. In my case we plan to divide the work based on some conditions as am going to query the source system frequently to populate the data streams.  I this scenario , how does the workers coordinate and pull the tasks to execute. Does it use a shared space like a dedicated kafka topic or zookeeper to do the assignments. Also , in future if my data condition changes , it needs reconfiguration - correct? Please help clarify .

Also , is there any step by step guide for setting up the multi worker environment. That would be of real help.

**Comment by ewencp** [comment]
1. The workers use the same group coordination functionality the Kafka brokers provide for consumer groups. Currently the assignment strategy is simple round-robin, although it should be possible in the future to swap out different assignment strategies, just like the consumer can.
2. The unit of work is a connector or task, both of which are continuously running. It doesn't behave like a task queue (which is what it sounds like you're describing in your question). There is a shared topic for connector & task configurations and another topic to track offset information.
3. Yes, the workers are containers for multiple tasks, and the reason for having two concepts (tasks and workers) is that they do not map 1-to-1.
4. I'm not sure what you mean by your data condition changing, but yes, if you need to modify how the connector pulls data from another system, you will need to reconfigure.
5. Take a look at the [distributed mode](http://docs.confluent.io/2.0.0/connect/userguide.html#distributed-mode) description for workers. There is nothing connector-specific about setting up distributed mode. You simply start up multiple worker instances, each using the same group ID, config topic, and offsets topic (and other common settings such as the Converter classes should also be the same). Once they are running, you can submit connectors via the REST API. You can easily start with a single node for testing and then add more to build up your cluster.

By the way, we also have a [mailing list](https://groups.google.com/forum/#!forum/confluent-platform) where questions like these might get more eyes on them since fewer people are watching this specific connector repository.

**Comment by SaravananVT** [comment]
Thanks a lot Ewen for the prompt reply. Appreciate it.. 

Just one more last question , as the input data streams are partitioned ( i.e in the jdbc example - users , products table). Does each tasks tie up to the partitions. if not , how does the data integrity is maintained when multiple tasks reads from the same partition and how can we guarantee we dont read the same source data again ( For ex - in the query mode).

**Comment by ewencp** [comment]
@SaravananVT At any given time, each partition is assigned to exactly one task (but each task may be assigned many partitions). This guarantees that only one task will be reading from the table at a time. If there is a change in the number of partitions or the maximum number of tasks the connector may create, then updated task configurations (including partition assignments) are created, old tasks are stopped (giving the opportunity to flush data and commit offsets), and the new tasks are started with the new assignments.

This does mean that you cannot parallelize copying data from a single table. For a JDBC connector this isn't an issue -- 1 task is generally going to be sufficient to copy data from 1 table. For other types of connectors, they might try to break the work into finer granularity partitions to enable more parallelism.

In query mode, there will only be a single task.

**Comment by SaravananVT** [comment]
Thanks .. That clarifies.. I am actually dealing with a mainframe data sets ( like single large data source for now) which are exposed as RESTful services and i am planning to divide the partitions\tasks based on applying  conditions to query the REST Services and have max of 4 or 5 tasks. Does that makes sense.?

**Comment by ewencp** [comment]
@SaravananVT That sounds like it makes sense -- really any approach is fine as long as it cleanly partitions the data so there is no overlap. One thing you might want to keep in mind is future growth -- you're generally better off with finer granularity partitions (e.g. make sure you can generate 25 or 100 partitions) and just use fewer tasks if you don't need the parallelism. That will give you room to grow in the future simply by increasing the maximum # of tasks (which will result in partitions being rebalanced across the new, larger number of tasks).

**Comment by SaravananVT** [comment]
Perfect thanks .. I am going to start the work.. Shall share the results when am done

**Comment by oleg-smith** [comment]
@ewencp Could you please clarify the case where new table is detected and mode is distributed - will every connector request to reconfigure tasks? So everything will be reconfigured N times though leader instead of one?

**Comment by ewencp** [comment]
@oleg-smith Each connector can have a thread which is scheduled to execute on workers just like tasks. So for each JDBC connector there will be one thread on one of the workers that tracks the tables. When it detects a new table, the reconfiguration only happens once -- it tells the framework that it wants to use the new configuration. Then the framework across all nodes detects this (as the data is written to Kafka) and they all coordinate to then rebalance the new set of tasks/connectors across the workers.

**Comment by oleg-smith** [comment]
@ewencp Do you mean there is always single instance of connector in distributed mode?
