### ISSUE TITLE
Database schema support 

### ISSUE THREAD

**Issue by tma625** [confluentinc/kafka-connect-jdbc#32]
I have a Postgres database with multiple tables of the same name, but in different schemas. I'm not seeing a way to specify the schemas for the tables in the properties file, and if I provide the entire "schema.tablename" as the name in the properties file that doesn't seem to work either. 

It looks like there are a couple of problems causing this. First, `JdbcUtils.getTables` returns just a list of table names (without the schema name prepended). Second, also in JdbcUtils, whenever `DatabaseMetaData.getTables` is called, it's always called with `null` as the second parameter for the schema, which results in all of the schemas being searched. 

I think the fix would be allowing for the "schema.tablename" syntax in the table whitelist or blacklist, and then parsing schema out of this string. `TableQuerier` would also need an additional field for this schema in order to pass this schema along to `JdbcUtils`.

I've got a proof of concept working, but I was curious if this was a known issue or if support would be added soon?

Thanks

**Comment by ewencp** [comment]
@tma625 You're correct that we are currently limited to a single schema. This was an intentional choice for the first release -- there's a limited number of features we could fit into this first round of development. We know that this will be important functionality and it will be added.

I actually don't think it will be that difficult to add -- as you pointed out, there are a couple of key places that we need to be careful about specifying or retrieving the schema. From there, hopefully most of the rest of the fallout is mostly mechanical changes to use schema + table rather than just table.

**Comment by shikhar** [comment]
This was addressed with #109
