### ISSUE TITLE
kafka-connect-jdbc source to Oracle constantly running slow query against ALL_OBJECTS

### ISSUE THREAD

**Issue by andrewinwlg** [confluentinc/kafka-connect-jdbc#346]
Hi, our DBA noticed the following query constantly running from each Kafka JDBC connector, i.e. every time it completes (which takes several minutes), it runs again right away:

```
SELECT NULL AS table_cat,
o.owner AS table_schem,
o.object_name AS table_name,
o.object_type AS table_type,
NULL AS remarks
FROM all_objects o
WHERE o.owner LIKE :1 ESCAPE '/'
AND o.object_name LIKE :2 ESCAPE '/'
AND o.object_type IN ('TABLE', 'SYNONYM', 'VIEW')
ORDER BY table_type, table_schem, table_name
```

I can see that this is likely being called from JdbcUtils.java (likely getTables, line 89), but I don't understand why it needs to constantly execute this query (can't it just run once at startup??? or periodically at a configurable interval), and how to disable it.  To make matters worse, I think it is just passing in "%" as the bind variable which forces full table scans.  Can anyone please help?  

The problem is we plan on running dozens of connectors, so if each one constantly polls the ALL_OBJECTS view, we will have dozens of extra connections tying up heaps of valuable DB resources.

Note we are running our connectors in timestamp mode.

**Comment by rhauch** [comment]
The [line you cite above](https://github.com/confluentinc/kafka-connect-jdbc/blob/master/src/main/java/io/confluent/connect/jdbc/util/JdbcUtils.java#L89) is actually a JDBC driver method that returns the list of tables in a database. The JDBC source connector uses this method to see whether there are new tables that satisfy the whitelist and blacklist filters and that should be queried. You can control how often this occurs with the `table.poll.interval.ms` source connector configuration property, which defaults to 60 seconds. Note that you if you increase this value, it may take longer for the connector to recognize a newly-added table. If you're situation is that you're explicitly listing all tables to be queried and don't care about other tables if/when they're added, then you 

Because it's a , so we have very little insight into the actual query that results from the call nor the performance of the query. (The names in the query suggest the DBMS is Oracle. Can you confirm? Can you specify which JDBC driver you're using?)

The reason the JDBC source connector does this is to know as soon as possible if/when the set of tables change.

**Comment by andrewinwlg** [comment]
Thanks!  We'll give that a try.

**Comment by soin08** [comment]
In my case this query was taking so long that my POST request to the Kafka Connect REST API thew 500 error. Got around this by specifying `query=select * from table` in the `query` field and setting ` table.types="FAKE_TYPE"`. This way Oracle performs select from `all_objects ` very quickly.

**Comment by cuneytykaya** [comment]
hi @rhauch, is there any way two completely disable this (table.poll.interval.ms) paramater? We dont want to execute this query. 
Is closing this completely cause other problems?
