### ISSUE TITLE
Invalid data for a Oracle number field using jdbc sink connector

### ISSUE THREAD

**Issue by ksbalan2018** [confluentinc/kafka-connect-jdbc#450]
Field type in oracle was number(15,5) which got converted to AVRO schema with type as bytes with scale 5. A value of 60 which is represented in kafka as "<" ( UTF8 Byte equivalent) got updated in the table column as 0.00060.  
Please note I have auto-generated the schema using a source connector and using the same schema for sink connector as well.

**Comment by rhauch** [comment]
What version of the connector were you using? 4.1.1 adds a new [`numeric.mapping` configuration option](https://docs.confluent.io/4.1.1/connect/connect-jdbc/docs/source_config_options.html#database) (added in #396) that gives a lot more control for numbers to be stored as primitive ints and decimals rather than BigDecimal (which Avro serializes as bytes). Note that to maintain backward compatibility, this feature must be enabled to be used.

I'm going to mark this as closed; feel free to reopen if that doesn't fix your issue.
