### ISSUE TITLE
kafka-connect-jdbc topic key issue

### ISSUE THREAD

**Issue by fzucxl** [confluentinc/kafka-connect-jdbc#521]
hello!

   I am a kafka connect user.I have a problem when use kafka-connect-jdbc for exporting data from mysql.

   the problem is the topic who have more than one partition that is using for transforing can not input data into all partition but one.

  so, I read source code and discover that the class TimestampIncrementingTableQuerier(method extractRecord) do not assign the record key.so data always into one partition.

  code:
return new SourceRecord(partition, offset.toMap(), topic, record.schema(), record);//record.key is null

  can you help me ? or solve this problem in future version ?

Thank you!

**Comment by rhauch** [comment]
Right now, the only way to do this is with the [`ValueToKey`](https://docs.confluent.io/current/connect/transforms/valuetokey.html#valuetokey) Single Message Transform (SMT) to create a key from the fields in the record value. Once we add support for using keys in source records (#28), this should be a lot easier. 

Closing since this is a question.
