### ISSUE TITLE
Kafka Connector not able to create topic if auto creation is turned off

### ISSUE THREAD

**Issue by nik09541** [confluentinc/kafka-connect-jdbc#534]
Hi Guys
 I had a query regarding the topic creation. The scenario is that when I mention topic.prefix=test and table.whitelist= TEMPDATA in my source connector config , Kafka creates topic with name testTEMPDATA and polls data from TEMPDATA table in the database. For disabling it we do have a property
 auto.create.topics.enable=false which can be mentioned in server.properties.
 Now in case I provide this property in my config file auto creation gets disabled and topic-prefix is left blank ,kafka connector gives error :

[2018-11-21 11:53:24,005] WARN [Producer clientId=producer-1] Error while fetching metadata with correlation id 228 : {TRANSTEMP=UNKNOWN_TOPIC_OR_PARTITION} (org.apache.kafka.clients.NetworkClient)

I want a predefined topic which I should be mentioning in property file so that which kafka polls data from my table over that topic. Is there any way to do this by any property?

Please help.

**Comment by rhauch** [comment]
The JDBC source connector always writes to topics named `${topic.prefix}${tableName}`, where `${topic.prefix}` is the value of the `topic.prefix` configuration property, and `${tableName}` is the name of the DB table. If you leave the `topic.prefix` property blank, then the topic names will match the DB table name. This is simply how the connector is designed.

If you want to do something different, you can change the name of the topic to which messages are written using the [RegexRouter single message transform (SMT)](https://docs.confluent.io/current/connect/transforms/index.html). Be careful, though, because depending upon how you configure it the JDBC source connector might read multiple tables and thus write to multiple topics, and your RegexRouter SMT needs to handle all of the re-routing logic.

**Comment by nik09541** [comment]
Hi @rhauch 
I need to understand the regex in SMT. In case i do mention the property topics.regex= test.* in the connector.properties and leave the topics.prefix as blank , the topic is getting created with tablename(which has been said by you also). How does this regex pattern create a predefined topic to which consumer can listen . As per my understanding topics.regex is used to listen  in case we have multiple topics like test.test1, test.test2 ......... test.*  being created. I might not be correct  though.

Please correct me in case this is not fine. My point again remains unresolved which i asked in last post that  'I want a predefined topic which I should be mentioning in property file so that which kafka polls data from my table over that topic' .
