### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by criccomini** [confluentinc/kafka-connect-jdbc#58]
This isn't really an issue--more of an inquiry. We're poking at Kafka connect. Is there anything special that needs to happen to make the JDBC connector send to Kafka brokers with security enabled?

**Comment by ewencp** [comment]
@criccomini I actually just wrote some system tests to validate this: https://github.com/apache/kafka/pull/1141

The current setup isn't ideal because it requires duplicating security configs, but was necessary to support different configs on the Connect group member, producer and consumer. You'll use the same security configs across all three. You can see how to override producer and consumer settings here: http://docs.confluent.io/2.0.1/connect/userguide.html#overriding-producer-consumer-settings

So to do something simple like enable SSL (as described [here](http://docs.confluent.io/2.0.1/kafka/ssl.html)) you might use something like:

```
security.protocol=SSL
ssl.truststore.location=/var/private/ssl/kafka.client.truststore.jks
ssl.truststore.password=test1234
producer.security.protocol=SSL
producer.ssl.truststore.location=/var/private/ssl/kafka.client.truststore.jks
producer.ssl.truststore.password=test1234
consumer.security.protocol=SSL
consumer.ssl.truststore.location=/var/private/ssl/kafka.client.truststore.jks
consumer.ssl.truststore.password=test1234
```

**Comment by criccomini** [comment]
Awesome, thanks! I'll re-open if I have questions.
