### ISSUE TITLE
Rebalance cause missing record

### ISSUE THREAD

**Issue by fzucxl** [confluentinc/kafka-connect-jdbc#598]
Hi, I am using kafka connect by Distributed mode. and  connect mode is timestamp.

When I config connect-2, it will rebalance the connect-1 source work which is Extracting data. If connect-1 source work is extracting for T1(timestamp offset) which has 10000 record and noly 5000 already done.So the timestamp offset in config topic will be set T1, and the last 5000 record which timestamp is T1 can not be extracted forever because the query sql is : select * from table where modify_date > T1 and modify date < currentDbTimestamp.

have any one run into this problem?

**Comment by aliasbadwolf** [comment]
@fzucxl This will be the problem if you are just using timestamp mode and you have multiple records in  source db with same timestamp value. the best way out-of-th-box will be to be timestamp+incrementing mode if you have an incrementing column or if you can add an incrementing column to the table or have access to create a view with incrementing columns.

One other approach I am working on is to use k-streams the offsets topic for connector and reducing 1 millisecond from a configurable list of connector every time the connector commits the offset. This will however will read duplicates and will have to de-dup downstream. But its better to have duplicates than not having the records. Once I am done with the implementation and testing with this approach, will let you know as to how it worked out for me.

**Comment by gharris1727** [comment]
@fzucxl This is expected behavior, and @aliasbadwolf is exactly correct with their analysis.
Unfortunately this behavior also appears in other situations, such as when the number of records updated in a single time-step is more than `batch.size`, and is one of the pitfalls of timestamp-only mode. Unfortunately there's no change we could make to the connector, since we're up against the limits of timestamp precision, and can't determine which records have been read already and which have not.
