### ISSUE TITLE
 error when connect to DB2 for AS/400

### ISSUE THREAD

**Issue by hongjn** [confluentinc/kafka-connect-jdbc#61]
error message: No suitable driver found.

**Comment by ewencp** [comment]
@hongjn If you're using Confluent Platform, we ship a few open source JDBC drivers, but if you're looking to use any other databases you'll need to make sure the appropriate JDBC driver is on the classpath. Although drivers aren't connector plugins, the instructions for JDBC drivers and connector plugins are essentially identical -- you can follow [these instructions](http://docs.confluent.io/2.0.1/connect/userguide.html#installing-connector-plugins) if you're not sure how to install the driver.

Does adding the driver to your classpath resolve your error message?

**Comment by hongjn** [comment]
@ewencp I have added the driver jt400.jar to the classpath, but not resovle. 

It need to register the driver to DriverManager first. 

[https://www.ibm.com/support/knowledgecenter/ssw_i5_54/rzahh/jdbcdrvr.htm?lang=en](url)

**Comment by gwenshap** [comment]
You need to use the db2jcc jar (see here:
http://www-01.ibm.com/support/docview.wss?uid=swg21363866)

Gwen

**Comment by hongjn** [comment]
@gwenshap @ewencp thanks for all your answers.

I resolve the error by adding the following code at JdbcSourceConnector before `DriverManager.getConnection`
`DriverManager.registerDriver(new com.ibm.as400.access.AS400JDBCDriver());`

**Comment by ewencp** [comment]
@hongjn If that solution works for you that's great. We obviously can't add that directly to the JDBC connector code since it relies on the specific class being available.

This also generally shouldn't be needed -- since JDBC 4.0, drivers can be automatically discovered. Not sure why you would need to manually register it anymore.

In any case, if you need a solution that registers the driver but doesn't require recompiling the connector, you might be able to put this code in your own jar in a class's `static`, then include that jar on the classpath in addition to the connector jar.

**Comment by vishalpaalakurthi** [comment]
> @gwenshap @ewencp thanks for all your answers.
> 
> I resolve the error by adding the following code at JdbcSourceConnector before `DriverManager.getConnection`
> `DriverManager.registerDriver(new com.ibm.as400.access.AS400JDBCDriver());`

perfectly works, i too tried
