### ISSUE TITLE
Date type is converted to integer

### ISSUE THREAD

**Issue by hongjn** [confluentinc/kafka-connect-jdbc#64]
I am using DB2.
As the column type Date is transfered to integer, so after the data into Hive, it is a number.
why not puting the date into Hive directly ?
Very thanks.

**Comment by ewencp** [comment]
@hongjn This isn't well documented outside of the javadocs, but logical types like Date and Timestamp have a standardized underlying representation, see http://docs.confluent.io/2.0.1/connect/javadocs/org/apache/kafka/connect/data/Date.html for Date's. In this case, it's a standardized to number of days since Unix epoch. In Connect, you can identify that it is a Date by metadata carried with the schema, but that is being lost when translating into downstream systems.

There's been some discussion on the Kafka mailing list around other representations. But I'd say this is actually more of an issue with the HDFS connector, which should be able to preserve Dates as Date types, especially if Hive integration is enabled and we could translate that information to the Hive schema.

**Comment by hongjn** [comment]
@ewencp Yes, I am using HDFS connector, and Hive integration is enabled. Now how can I preserve Date types ?

**Comment by ewencp** [comment]
@hongjn Sorry, to clarify, the date is encoded as an integer and right now the HDFS connector doesn't check for logical types, like `Date`, that it can preserve. I've filed https://github.com/confluentinc/kafka-connect-hdfs/issues/49 to track the need for this support.

**Comment by hongjn** [comment]
@ewencp Thanks.

**Comment by rnpridgeon** [comment]
Per @ewencp's advice this issue has been moved to HDFS-Connect here: confluentinc/kafka-connect-hdfs#49
