### ISSUE TITLE
Schema is copied over each time a new record is added to kafka log

### ISSUE THREAD

**Issue by JamesLoyd** [confluentinc/kafka-connect-jdbc#682]
I am currently consuming a mssql db and I have found that everytime we consume a topic through kafka connect using the jdbc driver, that schema information is copied over every single time.

Is there a way for us to only have schema specified once? Since, it seems a bit redudant to copy over schema information for every single record. Or is this by design?

**Comment by gharris1727** [comment]
It is by design that the schema information is duplicated, since it could change between records if the table schema changes, such as during schema evolution. This duplication of schema information that you've noticed is one of the primary motivations for [Schema Registry](https://docs.confluent.io/current/schema-registry/index.html).
