### ISSUE TITLE
Phoenix support

### ISSUE THREAD

**Issue by yixin19** [confluentinc/kafka-connect-jdbc#684]
Is this connector working for Phoenix?

Didn't see phoenix dialect.

**Comment by aliasbadwolf** [comment]
Any database that which is not in the select dialects directly supported out-of-the-box of kafka connect will fall into GenericDialect. As long as there is a JDBC Driver and a valid connection URL supported by that driver (in the classpath) it should work.

Haven't tested with Phoenix yet, but have tested against a driver that exposes REST service as JDBC. Even that is supported and falls back to using GenericDialect.

**Comment by yixin19** [comment]
> Any database that which is not in the select dialects directly supported out-of-the-box of kafka connect will fall into GenericDialect. As long as there is a JDBC Driver and a valid connection URL supported by that driver (in the classpath) it should work.
> 
> Haven't tested with Phoenix yet, but have tested against a driver that exposes REST service as JDBC. Even that is supported and falls back to using GenericDialect.

Thanks for the reply. Just want to know to objectif of dialect if the genericDialect works. In memory, the sink connector throws an type unsupport exception for phoenix

**Comment by aliasbadwolf** [comment]
Design decisions around objectives is something which the maintainer could tell. What I could gather is that each data base behaves differently and in order to cater to those nuances the JDBC connector could have implemented based on those nuances specific to some of the popular databases. Thus having dialects for those popular databases and since there are tons of databases (read drivers; even for Non database systems) they practically cannot provide out of the box implementation for each and every one of those databases.

My comment was targeted towards JDBC source connectors (since the question didn’t mentioned source or sink). Sinks are particularly challenging and JDBC out of the box might not connect as Hbase (on top of which Phoenix runs as SQL layer) is essentially not a relational JDBC based database. 

There is a community sink connector for HBase you might want to take a look at

https://www.confluent.io/hub/dhananjaypatkar/kafka-connect-phoenix

**Comment by yixin19** [comment]
> d in order to cater to those nuances the JDBC connector could have implemented based on those nuances specific to some of the popular databases. Thus having dialects for those popular databases and since there are tons of databases (read drivers; even for Non database systems) they practically cannot provide out of the box implementation for each and every one of those databases.

Thanks a lot.
This hbase connector is not a mature connector, only has json support. 
So far I will use other ingestion
