### ISSUE TITLE
Cannot write into Postgresql view

### ISSUE THREAD

**Issue by olivierperes** [confluentinc/kafka-connect-jdbc#717]
The Kafka Connect JDBC sink only lists tables when scanning a Postgresql schema, meaning that one cannot write into an [updatable view](https://www.postgresql.org/docs/11/sql-createview.html#id-1.9.3.97.7.6.2). This is a pity because it would allow to solve real problems, especially working with data with types that kafka-connect-jdbc doesn’t know how to insert into Postgresql (UUID, enumerated types…).

If you have no plans to implement this yourselves, would you consider reviewing a PR?

**Comment by mariusneo** [comment]
@olivierperes i was in a similar situation as well (I needed a new feature in kafka-connect-jdbc) and I've created a pull request with tests and documentation which was fully reviewed reasonably fast (within approximately a week). So I'd suggest to create the pull request because it will eventually land on the `master` branch.

**Comment by olivierperes** [comment]
In the end we decided against using Kafka Connect for our current project, so I won’t be implementing this.
