### ISSUE TITLE
Reading from Kafka Topic for Custom Sink Connector

### ISSUE THREAD

**Issue by vvangari** [confluentinc/kafka-connect-jdbc#72]
I have written custom sink connector to database using sink connectors. But the problem i foresee is sink connector is able to fetch topic message only if the topic is available. If the topic is created after the start of sink connector. It's not able to fetch topic messages. Is there any solution to handle this? 

Looks like now it reads the topic after 5 minutes...how do i change the default consumer config values?

**Comment by ewencp** [comment]
@vvangari See the instructions here: http://docs.confluent.io/2.0.1/connect/userguide.html#overriding-producer-consumer-settings However, be careful about modifying the consumer settings here, if you decrease the metadata fetch interval you may increase load on the brokers unnecessarily. Not sure about your use case but since topic creation only happens once usually an interval like 5 minutes between metadata updates is sufficient.

**Comment by vvangari** [comment]
@ewencp Thank you for the info.
