### ISSUE TITLE
Config validation in Connector plugins should be able to deal with config providers.

### ISSUE THREAD

**Issue by klebervirgilio** [confluentinc/kafka-connect-jdbc#737]
Hi,

I'm trying to use the `VaultConfigProvider` to get the `connection.url` from Vault.

```json
"connection.url": "${vault:database:uri}"
```

The build process hits first [config validation endpoint.](https://docs.confluent.io/current/connect/references/restapi.html#put--connector-plugins-(string-name)-config-validate) which seems to not take ConfigProviders into account.

Error message:

```
Not a valid JDBC URL: ${vault:database:uri}
```

are there any plans to support for config providers in the validation?

My naive guess is, since the PROTOCOL_PATTERN:

```java
private static final Pattern PROTOCOL_PATTERN = Pattern.compile("jdbc:([^:]+):(.*)");
```
https://github.com/confluentinc/kafka-connect-jdbc/blob/master/src/main/java/io/confluent/connect/jdbc/dialect/DatabaseDialects.java#L63

Is used to validate the `jdbc` string:
```java
static JdbcUrlInfo extractJdbcUrlInfo(final String url) {
    Matcher matcher = PROTOCOL_PATTERN.matcher(url);
    if (matcher.matches()) {
      return new JdbcUrlDetails(matcher.group(1), matcher.group(2), url);
    }
    throw new ConnectException("Not a valid JDBC URL: " + url);
  }
```
https://github.com/confluentinc/kafka-connect-jdbc/blob/master/src/main/java/io/confluent/connect/jdbc/dialect/DatabaseDialects.java#L170-L176

We could change the Regexp to also match on vault and env config provider prefix? Something like that:

```java
private static final Pattern PROTOCOL_PATTERN = Pattern.compile("jdbc:([^:]+):(.*)|\$\{(env|vault)");
```

**Comment by klebervirgilio** [comment]
This PR should solve this issue https://github.com/confluentinc/kafka-connect-jdbc/pull/738

**Comment by gharris1727** [comment]
@klebervirgilio What Connect/Confluent Platform version are you seeing this issue on?

I found a KAFKA issue that may be relevant: [Kafka Connect ConfigProvider not invoked before validation](https://issues.apache.org/jira/browse/KAFKA-7225), and it indicates that this was fixed in Kafka 2.0.1 / 2.1.0 and CP 5.0.1 / 5.1.0.

**Comment by klebervirgilio** [comment]
@gharris1727 I think this is the version **Kafka Connect Version : 5.3.1-ccs**

**Comment by gharris1727** [comment]
@klebervirgilio I think that before the configuration gets into any of this code, it's supposed to be transformed by the config provider. I think permitting the un-transformed values to go any further than they do now violates some assumptions that the rest of the code is written with.

I think that the ConfigProvider may not be triggering properly. Can you post all of the `config.providers` config keys in your worker configuration, and any secrets file(s) that it uses? Please replace any addresses or secrets with dummy values before posting.

**Comment by klebervirgilio** [comment]
It looks like that:
```json
{
  "connection.user": "${vault:path/on/vault:DB_USER}",
  "connection.password": "${vault:path/on/vault:DB_PWD}",
  "connection.url": "${vault:path/on/vault:DB_URI}",
  "config.providers.vault.class": "com.fundingcircle.config.VaultConfigProvider",
  "config.action.reload": "restart",
  "config.providers": "vault",
  ...
}
```
I agree. I think that's the case as well.
> I think that the ConfigProvider may not be triggering properly

@gharris1727 I couldn't find in which point pf codebase the ConfigProvider is being triggered,  in fact, I actually think it is not being called at all on the https://docs.confluent.io/current/connect/references/restapi.html#put--connector-plugins-(string-name)-config-validate endpoint flow.

**Comment by gharris1727** [comment]
@klebervirgilio As far as I understand, this is the relevant code:

* [ConnectorPluginsResource::validateConfigs](https://github.com/apache/kafka/blob/trunk/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/rest/resources/ConnectorPluginsResource.java#L68)
* [AbstractHerder::validateConnectorConfig](https://github.com/apache/kafka/blob/trunk/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/AbstractHerder.java#L281)

Unfortunately I don't see any log messages on that code path to aid further debugging, but I have verified that config providers are being called in the code correctly.

I just noticed in your configuration, you're including both `connection.url` and `config.providers` in the same object. Is this accurate or did you simplify the configuration before posting?
I think the `connection.*` keys should be in the connector configuration, and the `config.*` keys should be in the worker configuration. These are two separate files/objects, and should not be combined, since the configs for one are meaningless in the other.

**Comment by gharris1727** [comment]
If you have any more questions, please re-open this issue and i'd be happy to answer them.
