### ISSUE TITLE
Deletes with not-null schema

### ISSUE THREAD

**Issue by maqroll** [confluentinc/kafka-connect-jdbc#742]
Maybe there is a subtle problem in handling deletes: [here](https://github.com/confluentinc/kafka-connect-jdbc/blob/master/src/main/java/io/confluent/connect/jdbc/sink/BufferedRecords.java#L87) 
 record.valueSchema() is used to detect deletes but [later](https://github.com/confluentinc/kafka-connect-jdbc/blob/master/src/main/java/io/confluent/connect/jdbc/sink/BufferedRecords.java#L171) record.value() is used.

So: if record.value() is null (and record.valueSchema() isn't) a delete is pushed to the database but none of the checks to make sure that upserts aren't shadowed by deletes are triggered. 

**This can provoke deletes gone missing at random.**

Shouldn't use the same check (i.e. record.value()) in both places?

In addition, the [documentation](https://docs.confluent.io/current/connect/kafka-connect-jdbc/sink-connector/sink_config_options.html#writes) does not indicate that value schema has to be null for deletions.

**Comment by maqroll** [comment]
@gharris1727 Could you have a look at this issue?

**Comment by gharris1727** [comment]
@maqroll Thanks for pointing this out, It definitely seems like there might be an issue here.

Reading through the code, I think the current schema-null-check is essentially a guard on the schema evolution, and it was co-opted to trigger the deletion behavior. I think the schema-null-check is still important, so maybe we can just add an additional value-null-check that catches this issue.

I would understand this bug as not properly handling (optional schema, null) deletions, which weren't considered when this feature was designed.

If you feel comfortable, could you open a PR against `5.3.x` so that we can backport this bugfix?

**Comment by maqroll** [comment]
PR #748

**Comment by gharris1727** [comment]
This was fixed by #748 .
