### ISSUE TITLE
Unable to specify multiple table PKs for syncing multiple datasets into mysql

### ISSUE THREAD

**Issue by SouravDa** [confluentinc/kafka-connect-jdbc#743]
Mysql JDBC sink configuration is as follows :

name=jdbc-sink
connector.class=io.confluent.connect.jdbc.JdbcSinkConnector
tasks.max=1
topics=prod_master,cust_master
connection.url=jdbc:mysql://<>
transforms=unwrap
transforms.unwrap.type=io.debezium.transforms.UnwrapFromEnvelope
auto.create=true
insert.mode=upsert
delete.enabled=true
pk.fields=prod_master.prod_id,cust_master.cust_id
pk.mode=record_key
table.name.format=master.prod_master
transforms.unwrap.drop.tombstones=false

Looks like Kafka connect cannot decode the relation between 
topics=prod_master,cust_master
pk.fields=prod_master.prod_id,cust_master.cust_id

**Comment by gharris1727** [comment]
@SouravDa Yes, this is expected behavior for the sink connector. If you specify multiple topics, the sink connector will expect records from all of those topics to contain all of the primary key fields.

This kind of workload, where the topics don't have the same columns, would need to be handled by two separate sink connectors, each configured to sink one topic to one table.

If you have any further questions, feel free to re-open this issue and we can discuss further.
