### ISSUE TITLE
Question: Capturing new entries and updates on a table with no timestamp

### ISSUE THREAD

**Issue by abduq** [confluentinc/kafka-connect-jdbc#773]
Hello,

Say i have a table that has [id], [date], [customer_id], [order_count]
and i would like to capture:
1- **new entries:** based on [id] which is a primary key
2- **updates:** If an existing id had a change  in order_count

note that i dont have the luxury to alter the table and add updated_at column

thanks

**Comment by gharris1727** [comment]
@abduq This is not possible with this connector out of the box, since the connector needs the ability to query for updated rows. Because each row doesn't contain enough information to determine whether it's been updated or not recently, you can't query for it.

You can run the connector in bulk mode, and it will just read the table repeatedly without any range querying. If you can assemble a query that only returns recently updated records (perhaps using a second table to keep state), you could use this connector to call that query and import the records.
