### ISSUE TITLE
Doubt about use jdbc sink connect 

### ISSUE THREAD

**Issue by winghuer520** [confluentinc/kafka-connect-jdbc#817]
As below picture , I use auto.create and auto.evolve  in sink connect json .But i have some doubt .
![微信图片_20200318152738](https://user-images.githubusercontent.com/47166389/76937336-91e05900-692f-11ea-8a42-2bd88af6223b.png)
![微信图片_20200318152727](https://user-images.githubusercontent.com/47166389/76937343-9573e000-692f-11ea-87ea-4d34da61f2cd.png)

Frist doubt . when  i  create a new table from source mysql  , and the table created by auto.create in sink postgres . But the column's sequence is different , and the postgres's table don't have any comment that used in mysql's table .  

Second doubt ,  if i want to change the table name created by auto.create  not as same as  the topic.name 
. what should i do ?

**Comment by winghuer520** [comment]
And when i try to alter my source mysql table column name , the sink postgres will not do the same change .  The sink task  will be killed if  insert a new record to mysql  table .
![微信图片_20200318162708](https://user-images.githubusercontent.com/47166389/76940535-68c2c700-6935-11ea-9b39-651d52431e61.png)

**Comment by gharris1727** [comment]
> But the column's sequence is different , and the postgres's table don't have any comment that used in mysql's table

Yes, the source and sink in this project are not aware of table comments, and they are not preserved when moving records from one database to another.

> if i want to change the table name created by auto.create not as same as the topic.name, what should i do

The `table.name.format` configuration controls the table name that each topic is written to, and will also change the name of the table which is auto-created.

> alter my source mysql table column name , the sink postgres will not do the same change

This is a schema-incompatible change, since the connector will treat the renamed column in mysql as a new required column, and will not know how to migrate rows that have already been written to postgres. If you want to perform a column rename in mysql, you will have to migrate the postgres tables yourself, since the connector won't perform any schema migrations besides adding optional columns.
