### ISSUE TITLE
have support of array scheme type

### ISSUE THREAD

**Issue by ZulfiqarAkram** [confluentinc/kafka-connect-jdbc#821]
This is data published on the topic. I want to add 'log' data into the database. Now you can see the type of 'log' key is Array. so it means 2 records add into the database. I don't know how to do that. I want to know what is the schema of this or other things that required.
table name is 'log' so only i want to add log data.
Thank you

```
{
  "user_id": "9b173fb21bda0c1056e8dac4bd4bcb36",
  "firearm_id": "5db857b01ba6c050ebdf311d1e4bcb46",
  "latitude": 37.5969494,
  "longitude": -77.7754312,
  "log": [
    {
      "timestamp": 132991613189,
      "roll": -0.06393359659461391,
      "pitch": -0.17433374048812103,
      "heading": 6.047561791419422
    },
    {
      "timestamp": 132991613189,
      "roll": -0.06393359659461391,
      "pitch": -0.17433374048812103,
      "heading": 6.047561791419422
    }
  ]
}
```

**Comment by gharris1727** [comment]
Unfortunately, there's no support for any higher-order data types (array, map, struct) in any of the database dialects that this connector implements.

If you want to add two records to the database, then you'll have to have two events in your input topic, and each will get written separately. Since you need to split one record into multiple, you can't use an SMT, and will need to write your own stream processing job, such as ksql or kafka streams.
