### ISSUE TITLE
TimestampConverter / Allow to specify a time zone when converting unix epoch to string

### ISSUE THREAD

**Issue by fml2** [confluentinc/kafka-connect-jdbc#825]
TimestampConverter can convert a unix epoch value (long; number of milliseconds since Jan 01 1970 00:00 GMT) to string. However, when doing such conversion, the string result depends on the time zone used.

TimestampConverter uses UTC (i.e. GMT) for the conversion and does not allow to change it. But I would need this in order to get the date/time representation in my local time zone.

So I propose to introduce another config parameter (optional) for "target.type=string": **timeZone** (use java name for that). If no time zone is specified, UTC should be used.

**Comment by gharris1727** [comment]
@fml2 There's already the `db.timezone` configuration that controls timezone-sensitive conversions with the database, is that usable and fix your timestamp conversions?

If not, can you provide more information about your configuration and driver, and an example of the timestamp conversions that you're seeing?

**Comment by fml2** [comment]
Frankly, I don't know. Until I read your reply, I didn't know there exists such thing as "JDBC time zone". How does it translate to the usual JDBC API? Or is it a Kafka invention?

Anyway, the description of the parameter states that it's used "when querying with time-based criteria".

My case is a conversion from Date to String. If I then put the string to the DB, I don't think Kafka will somehow adjust it. It will put is as is. But when converting the date to string, the fixed time zone "UTC" is used, see https://github.com/confluentinc/kafka/blob/d8cf253d2e4ee54e680b7dcb2c6027c59ca666aa/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/TimestampConverter.java#L86, https://github.com/confluentinc/kafka/blob/d8cf253d2e4ee54e680b7dcb2c6027c59ca666aa/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/TimestampConverter.java#L265 and https://github.com/confluentinc/kafka/blob/d8cf253d2e4ee54e680b7dcb2c6027c59ca666aa/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/TimestampConverter.java#L132.

**Comment by gharris1727** [comment]
This repository is for the JDBC Connector, and not the transforms that are used with this connector. If you're talking about using the [TimestampConverter from apache/kafka](https://github.com/apache/kafka/blob/655447140ea5d3a59743f4bf77c0af7e34e2d96e/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/TimestampConverter.java), and not the JDBC Connector, then this is not the right repository to make this change.

If you have an idea of how this functionality would work, you can implement and test it yourself, since the transforms are open-source, and not need to rely on this change being implemented in upstream kafka.

If you're using the JDBC Connector from this repository, then the `db.timezone` configuration [will feed into the JDBC driver](https://github.com/confluentinc/kafka-connect-jdbc/blob/99e6d715163c45465c85ab11b5a79b0907a29a1b/src/main/java/io/confluent/connect/jdbc/dialect/GenericDatabaseDialect.java#L1258) for the database you're using, and the database driver handles timezone conversions. This will only take place if you haven't already converted your dates to strings with the TimestampConverter, since this conversion only takes place for date/time/timestamp logical types.

**Comment by fml2** [comment]
Ok, I see that I filed the issue in the wrong repository. You can close the issue. Thank you.
