### ISSUE TITLE
How Kafka connect works with MySQL

### ISSUE THREAD

**Issue by KhoaNguyenDang121292** [confluentinc/kafka-connect-jdbc#826]
I am wondering that how kafka connect jdbc source is working with MySQL database?

Specific that how it creates "thread to monitor database changes"?

Anybody help me to figure it out please!

Thank you.

**Comment by gharris1727** [comment]
The "thread to monitor database changes" is the [TableMonitorThread](https://github.com/confluentinc/kafka-connect-jdbc/blob/master/src/main/java/io/confluent/connect/jdbc/source/TableMonitorThread.java). This thread periodically queries the database for a list of tables, and passes them through a configurable whitelist/blacklist. The connector then distributes those tables among all of the tasks, so that each table is read by only one task, and one task can potentially read many different tables.
