### ISSUE TITLE
End to end connect setup?

### ISSUE THREAD

**Issue by wmccullough** [confluentinc/kafka-connect-jdbc#91]
Hello,

Very anxious to begin using this for SQL Server. I'm struggling to find decent instructions for setting this up end to end. Many instructions seem to be missing the actual substantial information for getting this going. Any tips?

**Comment by ewencp** [comment]
What specifically are you not sure about? It's simple, but the [quickstart](http://docs.confluent.io/3.0.0/connect/intro.html#quickstart) actually covers how to setup an end-to-end pipeline. The only difference for a "real" pipeline is the type of connectors you instantiate and their configs.

For JDBC specifically, what's missing from http://docs.confluent.io/3.0.0/connect/connect-jdbc/docs/jdbc_connector.html ? I am sure there are gaps, but without more specific questions it's hard to know what more to include. Perhaps [this blog post](http://www.confluent.io/blog/how-to-build-a-scalable-etl-pipeline-with-kafka-connect) and the corresponding [VM](https://github.com/confluentinc/kafka-connect-blog) would be of interest?

**Comment by wmccullough** [comment]
The quickstart covers SQLLite. I know that Confluent ships the JDBC connector with SQLLite and PostgreSQL support. I'm struggling to get this setup and configured for MSSQL. I don't place that burden on confluent because you DO explicitly state that the quickstart is doesn't include MSSQL, I'm more trying to see if anyone has an example of setting this up using the MSSQL server configuration settings.

This is my first foray into Kafka, so I'm likely just missing a good several more hours of reading about the connect api documentation.

Thank you for the information.

**Comment by ewencp** [comment]
No worries, it'd definitely be good to get examples of how to work with each database. This is especially true since some databases may need some config/connection URL tweaks to work well. At the moment we don't have suggested configs for MSSQL and I've only seen a handful of people testing with it. SQL Server is also notable for having very good support for CDC, see e.g. some discussion [here](https://github.com/confluentinc/kafka-connect-jdbc/issues/80). I know that's not immediately useful, but I'd imagine a few more besides yourself would also be interested if you come up with a good set of configs :)

**Comment by wmccullough** [comment]
I've been hammering it out. I'm almost there I think! Just getting a few class path exceptions. Once I get it I'd be happy to contribute a sample back.
